### ISSUE TITLE
Calling InstallPackage throws an invalid operation exception

### ISSUE THREAD

**Issue by PeterJausovec** [NuGet/NuGet.VisualStudioExtension#6]
Calling InstallPackage with any source throws the below exception: 

System.InvalidOperationException: The service 'Microsoft.Internal.VisualStudio.Shell.Interop.SVsUIThreadInvokerPrivate' must be installed for this feature to work.  Ensure that this service is available. HRESULT = 0x8000FFFF
   at Microsoft.VisualStudio.Shell.ThreadHelper.get_Invoker()
   at Microsoft.VisualStudio.Shell.ThreadHelper.InvokeOnUIThread(InvokableBase invokable)
   at Microsoft.VisualStudio.Shell.ThreadHelper.Invoke[TResult](Func`1 method)
   at NuGet.VisualStudio.VsHierarchyHelper.GetAllExpandedNodes(ISolutionManager solutionManager)
   at NuGet.VisualStudio.VsPackageInstaller.<InstallInternal>d__3d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.VsPackageInstaller.<>c__DisplayClassf.<<InstallPackage>b__e>d__11.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, NuGetVersion version, Boolean ignoreDependencies)
   at NuGet.VisualStudio.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Microsoft.VisualStudio.Office365.NuGet.NuGetPackageService.InstallPackage(String repository, Project targetProject, String packageId, String& installErrorMessage)

**Comment by danliu** [comment]
can you please try installing NuGet 3.0 Beta2 that was released? This issue should be fixed in that update.

http://blog.nuget.org/20150226/nuget-3.0-beta2.html

**Comment by PeterJausovec** [comment]
I am still seeing the same error with that build. Also, I am getting a different error if I try to manually install any NuGet package from the NuGet Package Manager:

System.ArgumentNullException: Value cannot be null.
Parameter name: regResource
   at NuGet.Client.V3DependencyInfoResource..ctor(HttpClient client, V3RegistrationResource regResource)
   at NuGet.Client.V3DependencyInfoResourceProvider.<TryCreate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Client.SourceRepository.<GetResourceAsync>d__8`1.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NuGet.Client.SourceRepository.GetResource[T](CancellationToken token)
   at NuGet.Client.SourceRepository.GetResource[T]()
   at NuGet.PackageManagement.ResolverGather.<GatherPackageDependencyInfo>b__8(SourceRepository s)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NuGet.PackageManagement.ResolverGather.<GatherPackageDependencyInfo>d__1c.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.ResolverGather.<GatherPackageDependencyInfo>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__91.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<PreviewInstallPackageAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.UI.UIActionEngine.<GetActions>d__2f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformAction>d__0.MoveNext()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: regResource
   at NuGet.Client.V3DependencyInfoResource..ctor(HttpClient client, V3RegistrationResource regResource)
   at NuGet.Client.V3DependencyInfoResourceProvider.<TryCreate>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Client.SourceRepository.<GetResourceAsync>d__8`1.MoveNext()<---

**Comment by PeterJausovec** [comment]
I am not seeing this issue anymore in the latest build.
